/*
** Copyright Microsoft, Inc. 1994 - 2000
** All Rights Reserved.
*/ -- In the NorthWind Db execute:
 -- SET NOCOUNT = ON;
 -- SET QUOTED_IDENTIFIER = ON;
 /* Set DATEFORMAT so that the date strings are interpreted correctly regardless of
   the default DATEFORMAT on the server.
*/
SET DATESTYLE TO mdy;


drop table if exists "dbo"."Categories";


drop table if exists "dbo"."Customers";


drop table if exists "dbo"."Employees";


drop table if exists "dbo"."Orders";


drop table if exists "dbo"."Order_Details";


drop table if exists "dbo"."Products";


drop table if exists "dbo"."Shippers";


drop table if exists "dbo"."Suppliers";


drop table if exists "dbo"."Territories";


drop SCHEMA if exists dbo;


CREATE SCHEMA dbo;


CREATE TABLE "dbo"."Employees" ( "EmployeeID" serial PRIMARY KEY,
																																	"LastName" varchar(20) NOT NULL,
																																	"FirstName" varchar(10) NOT NULL,
																																	"Title" varchar(30),
																																	"TitleOfCourtesy" varchar(25),
																																	"BirthDate" date, "HireDate" date, "Address" varchar(60),
																																	"City" varchar(30),
																																	"RegionId" int, "PostalCode" varchar(10),
																																	"Country" varchar(15),
																																	"HomePhone" varchar(24),
																																	"Extension" varchar(4),
																																	"Photo" bytea,
																																	"Notes" text, "ReportsTo" int, "PhotoPath" varchar(255),
																																	CONSTRAINT "FK_Employees_Employees"
																																FOREIGN KEY ("ReportsTo") REFERENCES "Employees" ("EmployeeID"), CONSTRAINT "CK_Birthdate" CHECK ("BirthDate" < CURRENT_DATE));


CREATE INDEX "LastName" ON "dbo"."Employees"("LastName");


CREATE INDEX "IX_Employees_PostalCode" ON "dbo"."Employees"("PostalCode");


CREATE TABLE "dbo"."Categories" ("CategoryID" serial PRIMARY KEY,
																																		"CategoryName" varchar (15) NOT NULL,
																																		"Description" text NULL,
																																		"Picture" bytea NULL);


CREATE INDEX "CategoryName" ON "dbo"."Categories"("CategoryName");


CREATE TABLE "dbo"."Customers" ("CustomerID" serial PRIMARY KEY,
																																	"CompanyName" varchar (40) NOT NULL,
																																	"ContactName" varchar (30) NULL,
																																	"ContactTitle" varchar (30) NULL,
																																	"Address" varchar (60) NULL,
																																	"City" varchar (30) NULL,
																																	"RegionId" int NULL,
																																	"PostalCode" varchar (10) NULL,
																																	"Country" varchar (30) NULL,
																																	"Phone" varchar (24) NULL,
																																	"Fax" varchar (24) NULL);


CREATE INDEX "City" ON "dbo"."Customers"("City");


CREATE INDEX "CompanyName" ON "dbo"."Customers"("CompanyName");


CREATE INDEX "PostalCode" ON "dbo"."Customers"("PostalCode");


CREATE INDEX "Region" ON "dbo"."Customers"("RegionId");


CREATE TABLE "Shippers" ("ShipperID" serial PRIMARY KEY,
																										"CompanyName" varchar (40) NOT NULL,
																										"Phone" varchar (24) NULL);


CREATE TABLE "dbo"."Suppliers" ("SupplierID" serial PRIMARY KEY,
																																	"CompanyName" varchar (40) NOT NULL,
																																	"ContactName" varchar (30) NULL,
																																	"ContactTitle" varchar (30) NULL,
																																	"Address" varchar (60) NULL,
																																	"City" varchar (30) NULL,
																																	"RegionId" int NULL,
																																	"PostalCode" varchar (10) NULL,
																																	"Country" varchar (30) NULL,
																																	"Phone" varchar (24) NULL,
																																	"Fax" varchar (24) NULL,
																																	"HomePage" text NULL);


CREATE INDEX "IX_Suppliers_CompanyName" ON "dbo"."Suppliers"("CompanyName");


CREATE INDEX "IX_Suppliers_PostalCode" ON "dbo"."Suppliers"("PostalCode");


CREATE TABLE "dbo"."Orders" ("OrderID" "int" GENERATED BY DEFAULT AS IDENTITY
																																	(START WITH 1 INCREMENT BY 1) NOT NULL,
																														"CustomerID" "int" NULL,
																														"EmployeeID" "int" NULL,
																														"OrderDate" "datetime" NULL,
																														"RequiredDate" "datetime" NULL,
																														"ShippedDate" "datetime" NULL,
																														"ShipperID" "int" NULL,
																														"Freight" "money" NULL CONSTRAINT "DF_Orders_Freight" DEFAULT (0), "ShipName" nvarchar (40) NULL,
																														"ShipAddress" nvarchar (60) NULL,
																														"ShipCity" nvarchar (30) NULL,
																														"ShipRegion" nvarchar (15) NULL,
																														"ShipPostalCode" nvarchar (10) NULL,
																														"ShipCountry" nvarchar (30) NULL,
																														CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderID"), CONSTRAINT "FK_Orders_Customers"
																													FOREIGN KEY ("CustomerID") REFERENCES "dbo"."Customers" ("CustomerID"), CONSTRAINT "FK_Orders_Employees"
																													FOREIGN KEY ("EmployeeID") REFERENCES "dbo"."Employees" ("EmployeeID"), CONSTRAINT "FK_Orders_Shippers"
																													FOREIGN KEY ("ShipperID") REFERENCES "dbo"."Shippers" ("ShipperID"));


CREATE INDEX "CustomerID" ON "dbo"."Orders"("CustomerID");


CREATE INDEX "CustomersOrders" ON "dbo"."Orders"("CustomerID");


CREATE INDEX "EmployeeID" ON "dbo"."Orders"("EmployeeID");


CREATE INDEX "EmployeesOrders" ON "dbo"."Orders"("EmployeeID");


CREATE INDEX "OrderDate" ON "dbo"."Orders"("OrderDate");


CREATE INDEX "ShippedDate" ON "dbo"."Orders"("ShippedDate");


CREATE INDEX "ShippersOrders" ON "dbo"."Orders"("ShipperID");


CREATE INDEX "ShipPostalCode" ON "dbo"."Orders"("ShipPostalCode");


CREATE TABLE "Products" ("ProductID" "int" GENERATED BY DEFAULT AS IDENTITY
																													(START WITH 1 INCREMENT BY 1) NOT NULL,
																										"ProductName" nvarchar (40) NOT NULL,
																										"SupplierID" "int" NULL,
																										"CategoryID" "int" NULL,
																										"QuantityPerUnit" nvarchar (20) NULL,
																										"UnitPrice" "money" NULL CONSTRAINT "DF_Products_UnitPrice" DEFAULT (0), "UnitsInStock" "smallint" NULL CONSTRAINT "DF_Products_UnitsInStock" DEFAULT (0), "UnitsOnOrder" "smallint" NULL CONSTRAINT "DF_Products_UnitsOnOrder" DEFAULT (0), "ReorderLevel" "smallint" NULL CONSTRAINT "DF_Products_ReorderLevel" DEFAULT (0), "Discontinued" "bit" NOT NULL CONSTRAINT "DF_Products_Discontinued" DEFAULT (0), CONSTRAINT "PK_Products" PRIMARY KEY ("ProductID"), CONSTRAINT "FK_Products_Categories"
																									FOREIGN KEY ("CategoryID") REFERENCES "dbo"."Categories" ("CategoryID"), CONSTRAINT "FK_Products_Suppliers"
																									FOREIGN KEY ("SupplierID") REFERENCES "dbo"."Suppliers" ("SupplierID"), CONSTRAINT "CK_Products_UnitPrice" CHECK (UnitPrice >= 0), CONSTRAINT "CK_ReorderLevel" CHECK (ReorderLevel >= 0), CONSTRAINT "CK_UnitsInStock" CHECK (UnitsInStock >= 0), CONSTRAINT "CK_UnitsOnOrder" CHECK (UnitsOnOrder >= 0));


CREATE INDEX "CategoriesProducts" ON "dbo"."Products"("CategoryID");


CREATE INDEX "CategoryID" ON "dbo"."Products"("CategoryID");


CREATE INDEX "ProductName" ON "dbo"."Products"("ProductName");


CREATE INDEX "SupplierID" ON "dbo"."Products"("SupplierID");


CREATE INDEX "SuppliersProducts" ON "dbo"."Products"("SupplierID");


CREATE TABLE "Order_Details" ("OrderID" "int" NOT NULL,
																															"OrderDetailID" "int" GENERATED BY DEFAULT AS IDENTITY
																																		(START WITH 1 INCREMENT BY 1) NOT NULL,
																															"ProductID" "int" NOT NULL,
																															"UnitPrice" "money" NOT NULL CONSTRAINT "DF_Order_Details_UnitPrice" DEFAULT (0), "Quantity" "smallint" NOT NULL CONSTRAINT "DF_Order_Details_Quantity" DEFAULT (1), "Discount" "real" NOT NULL CONSTRAINT "DF_Order_Details_Discount" DEFAULT (0), CONSTRAINT "PK_Order_Details" PRIMARY KEY ("OrderID",
																																																																																																																																																																																																																																																																																																																															"OrderDetailID"), CONSTRAINT "FK_Order_Details_Orders"
																														FOREIGN KEY ("OrderID") REFERENCES "dbo"."Orders" ("OrderID"), CONSTRAINT "FK_Order_Details_Products"
																														FOREIGN KEY ("ProductID") REFERENCES "dbo"."Products" ("ProductID"), CONSTRAINT "CK_Discount" CHECK (Discount >= 01)), CONSTRAINT "CK_Quantity" CHECK (Quantity > 0), CONSTRAINT "CK_UnitPrice" CHECK (UnitPrice >= 0) );


CREATE INDEX "OrderID" ON "dbo"."Order_Details"("OrderID");


CREATE INDEX "OrdersOrder_Details" ON "dbo"."Order_Details"("OrderID");


CREATE INDEX "ProductID" ON "dbo"."Order_Details"("ProductID");


CREATE INDEX "ProductsOrder_Details" ON "dbo"."Order_Details"("ProductID");


CREATE TABLE "Regions" ("RegionID" int GENERATED BY DEFAULT AS IDENTITY
																												(START WITH 1 INCREMENT BY 1) NOT NULL,
																									"RegionDescription" nchar (50) NOT NULL);


CREATE TABLE Territories ("TerritoryID" int GENERATED BY DEFAULT AS IDENTITY
																														(START WITH 1 INCREMENT BY 1) NOT NULL,
																											"TerritoryDescription" nchar (50) NOT NULL,
																											"RegionID" int NOT NULL);